//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.echo.ios.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=\".\\GbmcDB.sqlite\";default timeout=3000;cache size=20000")]
        public string GbmcDBConnectionString {
            get {
                return ((string)(this["GbmcDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=gbrm.km.yn;Initial Catalog=yngbdb1;User ID=sa;Password=yngbhyt")]
        public string yngbdb1ConnectionString {
            get {
                return ((string)(this["yngbdb1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("电子名册离线数据生成工具 for RM")]
        public string STR_TITLE {
            get {
                return ((string)(this["STR_TITLE"]));
            }
            set {
                this["STR_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQL服务器检测...")]
        public string STR_CHECKSQL {
            get {
                return ((string)(this["STR_CHECKSQL"]));
            }
            set {
                this["STR_CHECKSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("客户端检测....")]
        public string STR_CHECKSQLITE {
            get {
                return ((string)(this["STR_CHECKSQLITE"]));
            }
            set {
                this["STR_CHECKSQLITE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("同步数据(&S)")]
        public string STR_EXPORT {
            get {
                return ((string)(this["STR_EXPORT"]));
            }
            set {
                this["STR_EXPORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("退出(&X)")]
        public string STR_EXIT {
            get {
                return ((string)(this["STR_EXIT"]));
            }
            set {
                this["STR_EXIT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQL服务器正常连接，地址：gbrm.km.yn 数据库：yngbdb1")]
        public string STR_CHKSQLOK {
            get {
                return ((string)(this["STR_CHKSQLOK"]));
            }
            set {
                this["STR_CHKSQLOK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQL服务器连接失败，请检查网络设置和服务器")]
        public string STR_CHKSQLERROR {
            get {
                return ((string)(this["STR_CHKSQLERROR"]));
            }
            set {
                this["STR_CHKSQLERROR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sqlite数据库正常连接")]
        public string STR_CHKSQLITEOK {
            get {
                return ((string)(this["STR_CHKSQLITEOK"]));
            }
            set {
                this["STR_CHKSQLITEOK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sqlite数据库连接失败，请检查数据库文件")]
        public string STR_CHKSQLITEERROR {
            get {
                return ((string)(this["STR_CHKSQLITEERROR"]));
            }
            set {
                this["STR_CHKSQLITEERROR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("正在同步单位树表")]
        public string STR_SYNC_UNIT {
            get {
                return ((string)(this["STR_SYNC_UNIT"]));
            }
            set {
                this["STR_SYNC_UNIT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("正在同步领导干部表")]
        public string STR_SYNC_GBMC {
            get {
                return ((string)(this["STR_SYNC_GBMC"]));
            }
            set {
                this["STR_SYNC_GBMC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("正在同步亲属关系表")]
        public string STR_SYNC_RELATE {
            get {
                return ((string)(this["STR_SYNC_RELATE"]));
            }
            set {
                this["STR_SYNC_RELATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("同步数据完成")]
        public string STR_SYNC_OVER {
            get {
                return ((string)(this["STR_SYNC_OVER"]));
            }
            set {
                this["STR_SYNC_OVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("正在同步 {0} ，第 {1} 条记录，共 {2} 条记录")]
        public string STR_SYNC_PROCESS {
            get {
                return ((string)(this["STR_SYNC_PROCESS"]));
            }
            set {
                this["STR_SYNC_PROCESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"数据成功同步\"")]
        public string STR_SYNC_OK {
            get {
                return ((string)(this["STR_SYNC_OK"]));
            }
            set {
                this["STR_SYNC_OK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GbmcDB.sqlite")]
        public string STR_DB_FILE {
            get {
                return ((string)(this["STR_DB_FILE"]));
            }
            set {
                this["STR_DB_FILE"] = value;
            }
        }
    }
}
